#!/usr/bin/env python3
"""Upsert the master video database into Supabase (table lynxr_videos).

Replaces export_web.py + data.enc: instead of encrypting a JSON blob and
committing it, rows live in Postgres behind RLS (signed-in users read, nobody
but the service role writes). Run after any merge or retag so the table never
diverges from output/master_video_database.csv.

Auth: needs SUPABASE_SERVICE_ROLE_KEY in .env (never commit it — it bypasses
RLS). Get it from Dashboard -> Settings -> API keys.

  ./venv/bin/python pipeline/export_supabase.py                       # upsert all rows
  ./venv/bin/python pipeline/export_supabase.py --sql output/load_videos.sql
      # no network: write a single INSERT ... ON CONFLICT statement to paste
      # into the dashboard SQL editor instead (first load / no service key).
      # Write it under output/ (gitignored) — it holds the plaintext database.
"""

import argparse
import csv
import json
import os
import ssl
import sys
import urllib.error
import urllib.request

# macOS system Python often ships without a usable CA bundle, so verify against
# certifi's instead of disabling verification.
try:
    import certifi
    SSL_CTX = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    SSL_CTX = ssl.create_default_context()

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER = os.path.join(ROOT, "output", "master_video_database.csv")

SB_URL = "https://esakjfogplfszievvabi.supabase.co"

# Mirrors the old export_web.py KEEP list: what the front end actually uses,
# plus the extra taxonomy dimensions from tag_extra_dims.py. Missing columns are
# tolerated (blank) so this runs against a master CSV predating those columns.
KEEP = [
    "video_id", "creator", "platform", "title",
    "views", "likes", "comments", "engagement_rate",
    "format_type", "hook_pattern", "niche_category", "target_audience",
    "data_source", "url",
    "length_bucket", "audio_trend", "cta_type", "visual_hook",
    "onscreen_text", "hook_delivery",
]
INT_FIELDS = {"views", "likes", "comments"}


def load_env(path):
    env = {}
    try:
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip()
    except FileNotFoundError:
        pass
    return env


def to_int(v):
    try:
        return int(float(str(v).replace(",", "") or 0))
    except ValueError:
        return 0


def read_rows():
    with open(MASTER, newline="", encoding="utf-8") as f:
        raw = list(csv.DictReader(f))
    rows = []
    seen = {}   # (platform, video_id) -> index in rows, so later wins
    for r in raw:
        row = {}
        for k in KEEP:
            v = (r.get(k) or "").strip()
            row[k] = to_int(v) if k in INT_FIELDS else v
        if not row["video_id"] or not row["platform"] or not row["url"]:
            print(f"  skipping row with missing key: {row.get('url') or row.get('title')!r}")
            continue
        # Postgres rejects a single INSERT that names the same conflict target
        # twice ("ON CONFLICT DO UPDATE command cannot affect row a second
        # time"), so collapse duplicate (platform, video_id) here, last wins.
        key = (row["platform"], row["video_id"])
        if key in seen:
            rows[seen[key]] = row
        else:
            seen[key] = len(rows)
            rows.append(row)
    return rows


def sql_quote(v):
    if isinstance(v, int):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def write_sql(rows, path):
    if not rows:
        sys.exit("no rows to write — is the master CSV empty?")
    cols = ["platform", "video_id"] + [k for k in KEEP if k not in ("platform", "video_id")]
    with open(path, "w", encoding="utf-8") as f:
        f.write("-- Generated by pipeline/export_supabase.py --sql. Contains the full\n")
        f.write("-- plaintext database: run in the dashboard SQL editor, NEVER commit.\n")
        f.write(f"insert into public.lynxr_videos ({', '.join(cols)}) values\n")
        for i, r in enumerate(rows):
            vals = ", ".join(sql_quote(r[c]) for c in cols)
            f.write(f"({vals}){',' if i < len(rows) - 1 else ''}\n")
        f.write("on conflict (platform, video_id) do update set\n")
        f.write(",\n".join(f"  {c} = excluded.{c}" for c in cols if c not in ("platform", "video_id")))
        f.write(",\n  updated_at = now();\n")
    print(f"wrote {path} ({len(rows)} rows) — paste into the SQL editor, do not commit")


def upsert(rows, key):
    batch_size = 500
    for i in range(0, len(rows), batch_size):
        batch = rows[i:i + batch_size]
        req = urllib.request.Request(
            SB_URL + "/rest/v1/lynxr_videos?on_conflict=platform,video_id",
            data=json.dumps(batch).encode(),
            headers={
                "apikey": key,
                "Authorization": f"Bearer {key}",
                "Content-Type": "application/json",
                "Prefer": "resolution=merge-duplicates",
            },
            method="POST",
        )
        # urlopen raises HTTPError on any 4xx/5xx before we could read res.status,
        # so a bad/expired key or a PostgREST rejection must be caught here — the
        # response body carries the actual reason. Batches are separate requests,
        # so a mid-run failure leaves earlier batches committed; the upsert is
        # idempotent, so fixing the cause and rerunning is safe.
        try:
            with urllib.request.urlopen(req, context=SSL_CTX) as res:
                if res.status not in (200, 201, 204):
                    sys.exit(f"upsert failed: HTTP {res.status} {res.read()[:300]}")
        except urllib.error.HTTPError as e:
            body = e.read()[:300].decode(errors="replace")
            sys.exit(f"upsert failed at rows {i}-{i + len(batch)} (earlier batches "
                     f"committed; rerun after fixing): HTTP {e.code} {body}\n"
                     f"If HTTP 401/403, check SUPABASE_SERVICE_ROLE_KEY in .env.")
        except urllib.error.URLError as e:
            sys.exit(f"upsert failed: cannot reach {SB_URL} — {e.reason}")
        print(f"  upserted {i + len(batch)}/{len(rows)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sql", metavar="PATH",
                    help="write an INSERT statement to PATH instead of calling the API")
    args = ap.parse_args()

    rows = read_rows()
    print(f"{len(rows)} rows from {os.path.relpath(MASTER, ROOT)}")

    if args.sql:
        write_sql(rows, args.sql)
        return

    key = load_env(os.path.join(ROOT, ".env")).get("SUPABASE_SERVICE_ROLE_KEY") \
        or os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not key:
        sys.exit("SUPABASE_SERVICE_ROLE_KEY not set in .env — add it (Dashboard -> "
                 "Settings -> API keys) or use --sql for a paste-into-dashboard file.")
    upsert(rows, key)
    print("done — verify: select count(*) from lynxr_videos;")


if __name__ == "__main__":
    main()
